[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "inquirer>=3.4.1",
    "pydantic-settings>=2.12.0",
    "rich>=14.0.0",
    "supabase>=2.24.0",
    "tenacity>=9.1.2",
]
